### ISSUE TITLE
KatMouse doesn't work after enabling the tab-scroller.

### ISSUE THREAD

**Issue by windvane** [nurupo/chrome-mouse-wheel-tab-scroller#3]
KatMouse doesn't work after enabling the tab-scroller.

**Comment by nurupo** [comment]
Sounds like MouseOnEvent library's mouse event listening somehow interferes with KatMouse.

No idea how to debug or fix that though. I don't really understand what MouseOnEvent library is doing, apart from calling into dlls and allocating C structures - it's rather unreadable.

**Comment by windvane** [comment]
I had closed KatMouse and found that tab-scroller is not working sometimes. I have to disable it and enable it again by right clicking the icon. Is there a way to restart tab-scroller more quickly? Thank you.

**Comment by nurupo** [comment]
>KatMouse doesn't work after enabling the tab-scroller.

>I had closed KatMouse and found that tab-scroller is not working sometimes.

These issues should be fixed in the new version, could you try it out?

>Is there a way to restart tab-scroller more quickly? Thank you.

You can now disable/enable the tab-scroller by left-clicking on its icon, instead of right-clicking and selecting Disable.

**Comment by windvane** [comment]
The issues are fixed in the new version. Thank you.
